<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<%@ taglib prefix="fn" uri="jakarta.tags.functions" %>
<fmt:setLocale value="vi_VN"/>
<c:set var="pageTitle" value="Giỏ hàng"/><c:set var="activeNav" value="cart"/>
<%@ include file="common/header.jspf" %>

<main id="main" class="shell page-main"><nav class="breadcrumbs"><a href="${pageContext.request.contextPath}/home">Tủ sách</a><span>/</span><span>Giỏ hàng</span></nav><div class="page-heading"><div><p class="eyebrow">NHỮNG CUỐN SÁCH BẠN CHỌN</p><h1>Giỏ hàng của bạn</h1><p>Mỗi cuốn sách là một người bạn mới.</p></div><a class="text-link small" href="${pageContext.request.contextPath}/home">← Tiếp tục chọn sách</a></div>
<c:if test="${not empty error}"><div class="error" role="alert"><c:out value="${error}"/></div></c:if>
<c:choose><c:when test="${empty items and empty invalidCart}"><div class="empty-state"><div class="empty-symbol">◇</div><h2>Giỏ hàng đang chờ câu chuyện đầu tiên</h2><p>Khám phá tủ sách và chọn cuốn sách dành cho bạn.</p><a class="button" href="${pageContext.request.contextPath}/home">Khám phá sách →</a></div></c:when><c:otherwise><div class="cart-layout"><div><div class="table-scroll"><table><thead><tr><th>Sách đã chọn</th><th>Số lượng</th><th>Thành tiền</th><th></th></tr></thead><tbody>
<c:forEach items="${items}" var="item"><tr><td><div class="table-product"><img data-cover data-placeholder="${pageContext.request.contextPath}/assets/images/book-placeholder.svg" src="${pageContext.request.contextPath}/<c:out value='${item.book.cover_image}'/>" alt=""><div><strong><a href="${pageContext.request.contextPath}/detail?id=${item.book.bookid}"><c:out value="${item.book.title}"/></a></strong><small><fmt:formatNumber value="${item.book.price}" maxFractionDigits="0"/> đ / cuốn</small></div></div></td><td>
<form method="post" action="${pageContext.request.contextPath}/cart"><input type="hidden" name="token" value="${cartToken}"><input type="hidden" name="action" value="update"><input type="hidden" name="bookid" value="${item.book.bookid}"><c:choose><c:when test="${item.limit > 0}"><div class="quantity-control"><button type="button" data-quantity="-1" aria-label="Giảm số lượng">−</button><input aria-label="Số lượng ${fn:escapeXml(item.book.title)}" type="number" name="quantity" min="1" max="${item.limit}" value="${item.quantity}" required><button type="button" data-quantity="1" aria-label="Tăng số lượng">+</button></div><div class="table-actions" style="margin-top:7px"><button class="button-outline">Cập nhật</button></div></c:when><c:otherwise><span class="status CANCELLED">Hết hàng</span></c:otherwise></c:choose><small class="muted">Tối đa ${item.limit} cuốn</small></form><c:if test="${item.quantity > item.limit}"><p class="error small">Số lượng vượt tồn kho. Vui lòng giảm hoặc xóa.</p></c:if></td>
<td><strong><fmt:formatNumber value="${item.subtotal}" maxFractionDigits="0"/> đ</strong></td><td><form class="table-actions" method="post" action="${pageContext.request.contextPath}/cart"><input type="hidden" name="token" value="${cartToken}"><input type="hidden" name="action" value="remove"><input type="hidden" name="bookid" value="${item.book.bookid}"><button class="button-danger" aria-label="Xóa ${fn:escapeXml(item.book.title)}">Xóa</button></form></td></tr></c:forEach>
<c:forEach items="${invalidCart}" var="entry"><tr><td>Sách mã ${entry.key}</td><td>${entry.value} cuốn</td><td colspan="2"><form method="post" action="${pageContext.request.contextPath}/cart"><input type="hidden" name="token" value="${cartToken}"><input type="hidden" name="action" value="remove"><input type="hidden" name="bookid" value="${entry.key}"><button class="button-danger">Xóa khỏi giỏ</button></form></td></tr></c:forEach></tbody></table></div><form class="clear-cart" method="post" action="${pageContext.request.contextPath}/cart" data-confirm="Xóa tất cả sách khỏi giỏ hàng?"><input type="hidden" name="token" value="${cartToken}"><input type="hidden" name="action" value="clear"><button class="button-outline button-small">Xóa toàn bộ giỏ</button></form></div>
<aside class="summary-card"><h2>Tóm tắt giỏ hàng</h2><div class="summary-row"><span>Số sách đã chọn</span><strong>${fn:length(items)} loại</strong></div><div class="summary-row"><span>Phương thức</span><span>COD</span></div><div class="summary-row summary-total"><span>Tổng cộng</span><strong><fmt:formatNumber value="${total}" maxFractionDigits="0"/> đ</strong></div><c:if test="${not empty items}"><a class="button button-full" href="${pageContext.request.contextPath}/checkout">Tiến hành thanh toán →</a></c:if><p class="summary-note">Bạn chỉ thanh toán khi nhận được sách.<br>Giá và tồn kho sẽ được kiểm tra lại.</p></aside></div></c:otherwise></c:choose></main>
<%@ include file="common/footer.jspf" %>