<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<%@ taglib prefix="fn" uri="jakarta.tags.functions" %>
<fmt:setLocale value="vi_VN"/>
<c:set var="pageTitle" value="Thanh toán COD"/><c:set var="activeNav" value="cart"/>
<%@ include file="common/header.jspf" %>

<main id="main" class="shell page-main"><nav class="breadcrumbs"><a href="${pageContext.request.contextPath}/home">Tủ sách</a><span>/</span><a href="${pageContext.request.contextPath}/cart">Giỏ hàng</a><span>/</span><span>Thanh toán</span></nav><div class="page-heading"><div><p class="eyebrow">SÁCH HAY SẮP ĐẾN TAY BẠN</p><h1>Hoàn tất đơn hàng</h1><p>Điền thông tin nhận sách và xác nhận thanh toán COD.</p></div></div>
<c:if test="${not empty error}"><div class="error" role="alert"><c:out value="${error}"/></div></c:if><div class="checkout-layout"><section class="panel"><form class="form" method="post" action="${pageContext.request.contextPath}/checkout"><input type="hidden" name="token" value="${cartToken}"><h2 class="checkout-section-title"><span class="number-circle">01</span>Thông tin nhận hàng</h2><div class="form-grid"><div><label for="recipient">Họ tên người nhận *</label><input id="recipient" name="recipient" maxlength="100" value="<c:out value='${empty delivery ? sessionScope.account.fullname : delivery.recipient}'/>" required autocomplete="name" placeholder="Nhập họ và tên"></div><div><label for="phone">Số điện thoại *</label><input id="phone" name="phone" maxlength="20" value="<c:out value='${empty delivery ? sessionScope.account.phone : delivery.phone}'/>" required type="tel" autocomplete="tel" placeholder="Ví dụ: 0901234567"></div><div class="full-span"><label for="address">Địa chỉ nhận sách *</label><textarea id="address" name="address" maxlength="500" required autocomplete="street-address" placeholder="Số nhà, đường, phường/xã, tỉnh/thành phố"><c:out value="${delivery.address}"/></textarea></div></div><h2 class="checkout-section-title" style="margin-top:32px"><span class="number-circle">02</span>Phương thức thanh toán</h2><div class="payment-choice"><input id="cod" type="radio" name="paymentMethod" value="COD" checked required><label for="cod" style="margin:0;font-weight:400"><strong>COD — Thanh toán khi nhận hàng</strong><p>Trả tiền mặt cho nhân viên giao hàng khi nhận sách.</p></label></div><button class="button-full">Xác nhận đặt hàng COD →</button><small style="text-align:center">Vui lòng kiểm tra thông tin nhận hàng trước khi xác nhận.</small></form></section>
<aside class="summary-card"><h2>Đơn hàng của bạn</h2><c:forEach items="${items}" var="item"><div class="order-mini"><img data-cover data-placeholder="${pageContext.request.contextPath}/assets/images/book-placeholder.svg" src="${pageContext.request.contextPath}/<c:out value='${item.book.cover_image}'/>" alt=""><div><strong><c:out value="${item.book.title}"/></strong><small>Số lượng: ${item.quantity}</small><span><fmt:formatNumber value="${item.subtotal}" maxFractionDigits="0"/> đ</span></div></div></c:forEach><div class="summary-row"><span>Thanh toán</span><strong>Khi nhận hàng</strong></div><div class="summary-row summary-total"><span>Tổng cộng</span><strong><fmt:formatNumber value="${total}" maxFractionDigits="0"/> đ</strong></div><a class="text-link small" href="${pageContext.request.contextPath}/cart">← Chỉnh sửa giỏ hàng</a></aside></div></main>
<%@ include file="common/footer.jspf" %>