<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<%@ taglib prefix="fn" uri="jakarta.tags.functions" %>
<fmt:setLocale value="vi_VN"/>
<c:set var="pageTitle" value="Khám phá sách"/><c:set var="activeNav" value="home"/>
<%@ include file="common/header.jspf" %>

<main id="main" class="shell">
<section class="hero"><div><p class="eyebrow">DÀNH CHO NHỮNG TÂM HỒN HAM ĐỌC</p><h1>Mở trang sách.<br>Mở một <em>thế giới.</em></h1><p>Tìm người bạn đồng hành tiếp theo, từ những câu chuyện đầy cảm hứng đến tri thức thay đổi cuộc sống.</p><div class="hero-actions"><a class="button" href="#catalog">Khám phá tủ sách <span>↗</span></a><a class="text-link" href="${pageContext.request.contextPath}/home?available=1#catalog">Sách sẵn có →</a></div></div>
<div class="hero-art" aria-label="Những cuốn sách nổi bật"><img class="hero-book first" src="${pageContext.request.contextPath}/assets/images/dac-nhan-tam.jpg" alt="Đắc nhân tâm"><img class="hero-book second" src="${pageContext.request.contextPath}/assets/images/tuoi-tre-dang-gia-bao-nhieu.jpg" alt="Tuổi trẻ đáng giá bao nhiêu"><img class="hero-book third" src="${pageContext.request.contextPath}/assets/images/nha-gia-kim.jpg" alt="Nhà giả kim"><span class="art-note">Đọc để<br>lớn lên.</span></div></section>
<div class="benefits"><div class="benefit"><span class="benefit-icon">◇</span><div><strong>Tủ sách chọn lọc</strong>Những trang đọc đáng giá</div></div><div class="benefit"><span class="benefit-icon">↗</span><div><strong>Đặt hàng dễ dàng</strong>Giỏ hàng và theo dõi đơn</div></div><div class="benefit"><span class="benefit-icon">✓</span><div><strong>Thanh toán COD</strong>Trả tiền khi nhận sách</div></div></div>
<section class="catalog" id="catalog"><div class="section-head"><div><p class="eyebrow">TỦ SÁCH HUY BOOKS</p><h2>Tìm cuốn sách của bạn</h2><p>${total} cuốn sách ${not empty q ? 'phù hợp với tìm kiếm' : 'đang chờ được khám phá'}</p></div></div>
<form class="search-toolbar" method="get" action="${pageContext.request.contextPath}/home#catalog"><div class="search-input"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="10" cy="10" r="6" stroke="currentColor" stroke-width="1.7"/><path d="m15 15 5 5" stroke="currentColor" stroke-width="1.7"/></svg><input name="q" maxlength="100" aria-label="Tìm sách" placeholder="Tên sách, tác giả hoặc ISBN..." value="<c:out value='${q}'/>"></div><select name="sort" aria-label="Sắp xếp"><option value="newest" ${sort == 'newest' ? 'selected' : ''}>Mới nhất</option><option value="price-asc" ${sort == 'price-asc' ? 'selected' : ''}>Giá: thấp đến cao</option><option value="price-desc" ${sort == 'price-desc' ? 'selected' : ''}>Giá: cao đến thấp</option><option value="title" ${sort == 'title' ? 'selected' : ''}>Tên sách A–Z</option></select><label class="checkbox-label"><input type="checkbox" name="available" value="1" ${available ? 'checked' : ''}>Còn hàng</label><button>Tìm kiếm</button></form>
<c:choose><c:when test="${empty books}"><div class="empty-state"><div class="empty-symbol">⌕</div><h2>Chưa tìm thấy cuốn sách phù hợp</h2><p>Thử một từ khóa khác hoặc xem toàn bộ tủ sách.</p><a class="button button-outline" href="${pageContext.request.contextPath}/home">Xem tất cả sách</a></div></c:when><c:otherwise>
<div class="book-grid"><c:forEach items="${books}" var="b"><article class="book-card"><a class="book-image" href="${pageContext.request.contextPath}/detail?id=${b.bookid}"><span class="stock-badge ${b.quantity <= 0 ? 'out' : ''}">${b.quantity > 0 ? 'CÒN HÀNG' : 'HẾT HÀNG'}</span><img data-cover data-placeholder="${pageContext.request.contextPath}/assets/images/book-placeholder.svg" src="${pageContext.request.contextPath}/<c:out value='${b.cover_image}'/>" alt="<c:out value='${b.title}'/>" loading="lazy"></a><div class="book-meta"><div class="authors"><c:choose><c:when test="${empty b.authors}">Huy Books tuyển chọn</c:when><c:otherwise><c:forEach items="${b.authors}" var="a" varStatus="loop"><c:out value="${a.author_name}"/>${loop.last ? '' : ' · '}</c:forEach></c:otherwise></c:choose></div><h3><a href="${pageContext.request.contextPath}/detail?id=${b.bookid}"><c:out value="${b.title}"/></a></h3><div class="book-meta-bottom"><span class="book-price"><fmt:formatNumber value="${b.price}" maxFractionDigits="0"/> đ</span><c:if test="${b.quantity > 0 and b.price != null and b.price >= 0}"><form class="quick-add" method="post" action="${pageContext.request.contextPath}/cart"><input type="hidden" name="token" value="${cartToken}"><input type="hidden" name="action" value="add"><input type="hidden" name="bookid" value="${b.bookid}"><input type="hidden" name="quantity" value="1"><button aria-label="Thêm ${fn:escapeXml(b.title)} vào giỏ">+ Thêm</button></form></c:if></div><div class="review-count">★ ${fn:length(b.ratings)} đánh giá</div></div></article></c:forEach></div>
<c:set var="paginationPath" value="/home"/><%@ include file="common/pagination.jspf" %></c:otherwise></c:choose></section>
<section class="reading-banner"><h2>“Một cuốn sách là một giấc mơ<br>mà bạn cầm trên tay.”</h2><p>Dành một chút thời gian cho bản thân.<br>Chọn một cuốn sách, pha một tách trà,<br>và để câu chuyện bắt đầu.</p></section></main>
<%@ include file="common/footer.jspf" %>