<%@ page contentType="text/html;charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="fmt" uri="jakarta.tags.fmt" %>
<%@ taglib prefix="fn" uri="jakarta.tags.functions" %>
<fmt:setLocale value="vi_VN"/>
<c:set var="pageTitle" value="Tổng quan quản trị"/><c:set var="activeNav" value="admin"/>
<%@ include file="../common/header.jspf" %>

<main id="main" class="shell page-main"><c:set var="adminTab" value="dashboard"/><%@ include file="../common/admin-nav.jspf" %><div class="page-heading"><div><p class="eyebrow">KHÔNG GIAN QUẢN TRỊ</p><h1>Xin chào, <c:out value="${sessionScope.account.fullname}"/>.</h1><p>Cùng chăm chút tủ sách và những đơn hàng hôm nay.</p></div><a class="button button-small" href="${pageContext.request.contextPath}/admin/books?action=add">+ Thêm sách</a></div>
<div class="stat-grid"><div class="stat-card featured"><span>DOANH THU COD ĐÃ THU</span><strong><fmt:formatNumber value="${stats.revenue}" maxFractionDigits="0"/> đ</strong><small>Chỉ tính đơn đã giao và thu tiền</small></div><div class="stat-card"><span>TỔNG ĐƠN HÀNG</span><strong>${stats.orderCount}</strong><small>${stats.pendingCount} đơn chờ xác nhận</small></div><div class="stat-card"><span>SÁCH TRONG TỦ</span><strong>${stats.bookCount}</strong><small>Đầu sách đang quản lý</small></div><div class="stat-card"><span>BẠN ĐỌC</span><strong>${stats.userCount}</strong><small>Tài khoản đã đăng ký</small></div></div>
<div class="section-head"><h2 style="font-size:26px;margin:0">Đơn hàng gần đây</h2><a class="text-link small" href="${pageContext.request.contextPath}/admin/orders">Xem tất cả →</a></div><div class="table-scroll"><table><thead><tr><th>Mã đơn</th><th>Ngày đặt</th><th>Người nhận</th><th>Tổng tiền</th><th>Trạng thái</th><th></th></tr></thead><tbody><c:forEach items="${orders}" var="o"><tr><td><strong>#HB${o.id}</strong></td><td>${o.createdLabel}</td><td><c:out value="${o.recipient}"/><small class="muted" style="display:block">${o.paymentLabel}</small></td><td><strong><fmt:formatNumber value="${o.total}" maxFractionDigits="0"/> đ</strong></td><td><span class="status ${o.status}">${o.statusLabel}</span></td><td><a class="text-link" href="${pageContext.request.contextPath}${activeNav == 'admin' ? '/admin/orders?id=' : '/order-success?id='}${o.id}">Chi tiết →</a></td></tr></c:forEach><c:if test="${empty orders}"><tr><td colspan="6" style="text-align:center;padding:45px">Chưa có đơn hàng trong danh sách này.</td></tr></c:if></tbody></table></div>
<div class="dashboard-bottom" style="margin-top:30px"><section class="panel"><h2>Chăm sóc tủ sách</h2><p class="muted small">Cập nhật bìa, tác giả, ngày xuất bản, giá và tồn kho để bạn đọc dễ dàng tìm cuốn sách phù hợp.</p><a class="button button-outline button-small" href="${pageContext.request.contextPath}/admin/books">Quản lý sách</a> <a class="button button-outline button-small" href="${pageContext.request.contextPath}/admin/authors">Quản lý tác giả</a></section><section class="panel"><h2>Sắp hết hàng</h2><c:forEach items="${stats.lowStock}" var="b"><div class="stock-row"><a href="${pageContext.request.contextPath}/admin/books?action=edit&id=${b.bookid}"><c:out value="${b.title}"/></a><span class="status PENDING">${b.quantity} cuốn</span></div></c:forEach><c:if test="${empty stats.lowStock}"><p class="muted small">Tồn kho đang ổn định.</p></c:if></section></div></main>
<%@ include file="../common/footer.jspf" %>